### ISSUE TITLE
Openfoam function support

### ISSUE THREAD

**Issue by starflame-Qot** [vttresearch/gpuFoam#1]
Hello, this is a tool that interests me a lot. I'd like to see if it can be extended to AMR. and whether its energy equation can be further extended to the sensibleInternalEnergy.

Looking forward to hearing from you.

**Comment by hamsteri15** [comment]
Hello, 
since chemistry is independent of the mesh, using the gpu chemistry solvers should already work. However, it hasn't been tested, mostly because none of the complex chemistry tutorials use AMR. 

Similar thing applies to the choice of the energy transport variable. The reason I restricted the use for sensibleEnthalpy was that all of the complex chemistry tutorials in OpenFOAM used that. It appears, however, that the chemistry is independent of the choice of the energy equation transport variable and sensibleInternalEnergy already works. I have added a unit test for this and updated the gpu_chemistry/README.md accordingly.

Please let us know if you come up with any performance issues when using AMR with the gpu models.

**Comment by hamsteri15** [comment]
Fixed with commit c3302f7

**Comment by starflame-Qot** [comment]
Thanks very much for your reply. I'll install to try to use and I'll share if there are more verified AMR results.
